version: "3"
services:
  site:
    command: jekyll serve --drafts --force_polling --livereload
    image: jekyll/jekyll:latest
    volumes:
      - .:/srv/jekyll
    ports:
      - 4000:4000
      - 35729:35729
      - 3000:3000
      -   80:400
